SUPABASE_URL = "https://mctojlqphcoejyreiqgf.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jdG9qbHFwaGNvZWp5cmVpcWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MTMyMDYsImV4cCI6MjA4NjE4OTIwNn0.DMm7-O6Y4mWBowwFQ11YBl0PdQV5EHldRRHVaaOF35E"
